name: Python Linter

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 'x'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 'x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirement.txt

      - name: Lint
        run: |
          flake8 app.py
