name: Python Linter

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v4  # Ensure this is the latest version
        with:
          python-version: '3.9'  # Specify the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Lint app.py
        run: |
          flake8 app.py

      - name: Lint index.html
        run: |
          pip install beautifulsoup4
          python -m bs4 index.html
